BEGIN;

CREATE TABLE IF NOT EXISTS orders (
  id SERIAL PRIMARY KEY,
  idempotency_key TEXT UNIQUE,
  buyer VARCHAR(100) NOT NULL,
  product_id INTEGER NOT NULL,
  qty INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMIT;